### ISSUE TITLE
Wavetable Dropdown Menus and Preset List Not Loading

### ISSUE THREAD

**Issue by philjulian** [marcinpiet/nuPG_1.0#11]
This is on a Mac M2 / Sequoia 15.1 with the nuPG_2024_release under SC 3.13.0

The GUI opens fine but the dropdown menus that should be reading from Library/Application Support/SuperCollider/Extensions/nuPG_2024_release/TABLES and PRESETS are empty

Thanks for any help

**Comment by Elvis-Budingensis** [comment]
I had the same problem: the startup .scd-File has to be in the same directory as the installed quarks. That means  in ~ /Library/Application Support/SuperCollider/Extensions.  I solved it this way: create a symbolic link from the extensions nuPG_24_startUp to /Application. sudo ln -s ~/Library/Application\ Support/SuperCollider/Extensions/nuPG_24_startUp.scd  /Applications
